version: '3'
services:
  api:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/SteamDB
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    depends_on:
      - api
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=SteamDB